### ISSUE TITLE
"New page" and "new folder" buttons are not showing

### ISSUE THREAD

**Issue by GJRobert** [SoarinFerret/dokuwiki-plugin-pagebuttons#1]
These two buttons are not showing on Hogfather 51.3 (Stable) DokuWiki.
Only "delete page" button is showing. Almost the same as the menu button of `deletepagebutton` plugin.

**Comment by SoarinFerret** [comment]
I am on the Hogfather release as well and the 'New Page' and 'New Folder' buttons work for me.

These buttons create new subpages / folders, so you have to be in a folder already for them to work. If your URL is `/doku.php?id=start`, you technically are not in a folder so it doesn't make since to add a new page or folder.

However, if your URL is something like `/doku.php?id=wiki:start`, then both buttons should appear. I hope that makes sense?

**Comment by SoarinFerret** [comment]
I do see how it would be useful though to have the buttons appear all the time though. I will work on a patch this weekend to enable that functionality. In my head when I built it I didn't think about the buttons being there all the time

**Comment by GJRobert** [comment]
Hi, perhaps I should have clarified that, on my Hogfather, *none* of the pagebuttons appear. So it does not seem to be only with "new page" and "new folder" buttons. My bad.

The only delete button I see, seems to be from plugin:deletepagebutton, because the link on that specific button is http://localhost/dw-hog-test/doku.php?id=wiki:dokuwiki&do=deletepagebutton&sectok=bf95c81991217d3eca754beb6a6d57aa

After disabling plugin:deletepagebutton, I still see that button, and none of *pagebuttons* buttons of yours appear.

I have installed both your plugin and that plugin together, and I'm not sure this is the cause of the problem. I will install another new instance of DW to investigate this.

**Comment by MartijnRas** [comment]
I just installed this plugin for the first time in Hogfather, i can confirm that none of the buttons appear.

**Comment by SoarinFerret** [comment]
Ok, so I'm definitely not seeing what you two are seeing for whatever reason. Here is how I am testing:

1. Create a Dokuwiki container running the Hogfather release. Here is the `docker-compose.yml` I am using:
```yml
version: "3.3"
services:
  dokuwiki:
    environment:
      - DOKUWIKI_PASSWORD=password
    image: bitnami/dokuwiki:20200729
    ports:
      - "8080:8080"
```
2. Login to the web interface with `superuser` and `password` 
![image](https://user-images.githubusercontent.com/33401067/93154646-c3ad5f00-f6c9-11ea-8bb8-cd755e194efe.png)
3. Go to Admin ->Extension Manger -> Search and Install, and download the latest version of Page Buttons 
![image](https://user-images.githubusercontent.com/33401067/93154727-f8b9b180-f6c9-11ea-8b82-2d0c94bbef61.png)
4. On the root page (aka http://127.0.0.1:8080/start), you will not see any buttons, because a page does not exist.
![image](https://user-images.githubusercontent.com/33401067/93154805-2999e680-f6ca-11ea-8acf-09b5b63401d9.png)
5. Create the page, and now the "Delete Page" button appears 
![image](https://user-images.githubusercontent.com/33401067/93154855-54843a80-f6ca-11ea-92e9-d9c397d5375b.png)
6. Now, create a folder by going to `http://127.0.0.1:8080/start:start?do=edit`, put something in there and save.
7. Now on the right hand side, all 3 buttons appear: New Page, New Folder, and Delete 
![image](https://user-images.githubusercontent.com/33401067/93154982-a1681100-f6ca-11ea-9bf3-d3042d503bac.png)

Now, with that being said, that is how I have specifically been using this. As I mentioned above, it probably makes sense for the New Page / New Folder buttons to pretty much always be around, and they just go within the existing namespace. Instead of me just only allowing it on the "start" page of every folder.

I am working on a patch right now to enable this functionality, and I plan for it to become the new default. I'll update this issue once I create that. Please let me know how you are testing if you are not seeing the same thing! Thanks!

**Comment by SoarinFerret** [comment]
I have updated plugin so the new default functionality is to always show the newpage and newfolder buttons, as long as the page you are on already exists. This will simply add a new page / folder in your existing namespace.

Let me know if that helps! Thanks

**Comment by MartijnRas** [comment]
I was using the Adora Dark theme, the buttons indeed showed up when I switched back to the default theme.

**Comment by GJRobert** [comment]
> I have updated plugin so the new default functionality is to always show the newpage and newfolder buttons, as long as the page you are on already exists. This will simply add a new page / folder in your existing namespace.
> 
> Let me know if that helps! Thanks

@SoarinFerret I have updated to your newest version, and now the New Page and New Folder buttons are always around. Before updating, the two buttons are not shown for me even with `dokuwiki` default template and in the scenario within a folder.

Great to see the issue solved, thanks a lot! I like this handy plugin.
